<h3>Your Recommednations</h3>
<?php
$this->title = $this->escape("Your Anime List");
$this->headTitle($this->title);

if (!isset($this->username))
{
	 echo '<div class="success">You need to <a href="'.$this->url(array('controller'=>'login', 'action' => '')).'">login</a> to access this page.</div>';
} 
else
{
	if (($this->entries) > 0)
	{
        echo $this->form;
	}
	else
	{
		echo '<div class="notice">You have made no recommendations.</div>';	
	}
?>	
	<a href='<?=$this->url(array('controller'=>'user'),null, true)?>'>Return to your user page.</a>
<?php 
}
?>